language: rust

addons:
  apt:
    packages:
    - pandoc
    - libxml2-utils

matrix:
  include:
    - env: TARGET=docs
      script:
        - find . -name '*.md' -print0 | xargs -0 mdcheckr
    - env: TARGET=binary
      rust: nightly
      script:
        - cd binary
        - cargo check --target thumbv7em-none-eabihf
    - env: TARGET=firmware
      rust: nightly
      script:
        - cd firmware
        - cargo check --target thumbv7em-none-eabihf
        - cargo test
    - env: TARGET=board
      rust: nightly
      script:
        - cd board
        - cargo check --target thumbv7em-none-eabihf
        - cargo test
    - env: TARGET=utils
      rust: nightly
      script:
        - cd utils
        - cargo check --target thumbv7em-none-eabihf
        - cargo test

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/mdcheck"

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
