language: rust

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/gcc/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
