[workspace]

members = [
    "trustflight",
]

[profile.dev]
opt-level = 1
codegen-units = 16
debug = true
lto = false

[profile.release]
opt-level = "s"
codegen-units = 1 # better optimizations
debug = true
lto = true # better optimizations
