[package]
name = "trustflight_firmware"
categories = ["embedded", "no-std"]
authors = ["Emil Fresk <emil.fresk@gmail.com>"]
description = "A multirotor flight controller firmware you can trust"
keywords = ["arm", "cortex-m", "mav"]
license = "BSL-1.0"
repository = "https://github.com/korken89/trustflight_firmware"
version = "0.1.0"

[dependencies]
cortex-m = "*"
cortex-m-rt = "*"
# cortex-m-semihosting = "0.3.0"
# panic-semihosting = "0.2.0"
panic-abort = "*"

[dependencies.stm32f302x]
git = "https://github.com/korken89/stm32f302x"
branch = "master"
features = ["rt"]

[profile.release]
codegen-units = 1 # better optimizations
debug = true
lto = true # better optimizations
